subject_name: remove unused DirectoryName field
In practice we never examine the `untrusted::Input` field of
a `GeneralName::DirectoryName` variant. Nightly clippy is flagging this:

```
error: field `0` is never read
   --> src/subject_name/verify.rs:256:19
    |
256 |     DirectoryName(untrusted::Input<'a>),
    |     ------------- ^^^^^^^^^^^^^^^^^^^^
    |     |
    |     field in this variant
    |
    = note: `-D dead-code` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(dead_code)]`
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
    |
256 |     DirectoryName(()),
    |                   ~~
```

This commit switches the `GeneralName::DirectoryName` to be a variant
without any fields to resolve this finding. If we expand support for
`DirectoryName`'s in the future we can revisit.