x509: remove unused NameRelativeToCrlIssuer field
In practice we never examine the `untrusted::Input` field of
a `DistributionPointName::NameRelativeToCrlIssuer` variant. Nightly
clippy is flagging this:

```
error: field `0` is never read
  --> src/x509.rs:89:29
   |
89 |     NameRelativeToCrlIssuer(untrusted::Input<'a>),
   |     ----------------------- ^^^^^^^^^^^^^^^^^^^^
   |     |
   |     field in this variant
   |
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
   |
89 |     NameRelativeToCrlIssuer(()),
   |                             ~~
```

This commit switches
`DistributionPointName::NameRelativeToCrlIssuer` to be a variant without
any fields to resolve this finding.